=encoding utf-8

=begin fusion

@see_also Language::SX
@license  Language::SX

@taglist Language::SX::Manual::Tags
Find L<Language::SX> documentation by tag

@tagfile maint/tags.json

=end fusion






=head1 NAME

Language::SX::Manual::Tags - Find L<Language::SX> documentation by tag

=head1 TAGS

=head2 application

=over

=item * L<Language::SX/"General Syntax">

=item * L<Language::SX::Library::Data::Functions/"apply">

=item * L<Language::SX::Library::Data::Functions/"apply/list">

=item * L<Language::SX::Library::ScopeHandling/"apply!">

=back

=head2 arguments

=over

=item * L<Language::SX/"Modules">

=item * L<Language::SX::Library::Inserts>

=item * L<Language::SX::Library::ScopeHandling/"define">

=item * L<Language::SX::Library::ScopeHandling/"lambda">

=back

=head2 barewords

=over

=item * L<Language::SX/"Data Types">

=item * L<Language::SX::Runtime::Bareword>

=back

=head2 booleans

=over

=item * L<Language::SX/"Data Types">

=back

=head2 class methods

=over

=item * L<Language::SX::Library::Data::Objects/"class-invocant">

=back

=head2 conditionals

=over

=item * L<Language::SX::Library::Branching>

=back

=head2 context

=over

=item * L<Language::SX/"Context">

=item * L<Language::SX::Library::Data::Functions/"apply/list">

=back

=head2 equality

=over

=item * L<Language::SX::Library::Data::Numbers/"!=">

=item * L<Language::SX::Library::Data::Numbers/"==">

=item * L<Language::SX::Library::Data::Strings/"eq?">

=item * L<Language::SX::Library::Data::Strings/"ne?">

=back

=head2 filtering

=over

=item * L<Language::SX::Library::Data::Hashes/"hash-grep">

=item * L<Language::SX::Library::Data::Lists/"grep">

=back

=head2 functions

=over

=item * L<Language::SX::Library::Data::Functions>

=item * L<Language::SX::Library::ScopeHandling/"-E<gt>">

=item * L<Language::SX::Library::ScopeHandling/"E<lt>-">

=item * L<Language::SX::Library::ScopeHandling/"define">

=item * L<Language::SX::Library::ScopeHandling/"lambda">

=item * L<Language::SX::Library::ScopeHandling/"λ">

=back

=head2 hashes

=over

=item * L<Language::SX/"Data Types">

=item * L<Language::SX::Library::Data::Hashes>

=back

=head2 importing

=over

=item * L<Language::SX/"Modules">

=item * L<Language::SX::Library::Types/"import/types">

=back

=head2 iteration

=over

=item * L<Language::SX::Library::Data::Functions/"while">

=item * L<Language::SX::Library::Data::Lists/"for-each">

=item * L<Language::SX::Library::Data::Lists/"map">

=back

=head2 keywords

=over

=item * L<Language::SX/"Data Types">

=back

=head2 libraries

=over

=item * L<Language::SX/"Libraries">

=back

=head2 lists

=over

=item * L<Language::SX/"Data Types">

=item * L<Language::SX::Library::Data::Lists>

=item * L<Language::SX::Library::Quoting/"A note about quoted items">

=back

=head2 lower-case

=over

=item * L<Language::SX::Library::Data::Strings/"lower">

=item * L<Language::SX::Library::Data::Strings/"lower-first">

=back

=head2 math

=over

=item * L<Language::SX/"Data Types">

=item * L<Language::SX::Library::Data::Numbers>

=back

=head2 modules

=over

=item * L<Language::SX/"Modules">

=item * L<Language::SX::Library::Inserts>

=back

=head2 object methods

=over

=item * L<Language::SX/"Data Types">

=item * L<Language::SX::Library::Data::Objects/"object-invocant">

=back

=head2 objects

=over

=item * L<Language::SX/"Data Types">

=item * L<Language::SX::Library::Data::Objects>

=item * L<Language::SX::Library::Types/"Type Constraints != Objects">

=back

=head2 order determination

=over

=item * L<Language::SX::Library::Data::Functions/"rev-curry">

=item * L<Language::SX::Library::Data::Lists/"sort">

=item * L<Language::SX::Library::Data::Numbers/"E<lt>=E<gt>">

=item * L<Language::SX::Library::Data::Strings/"cmp">

=back

=head2 quoting

=over

=item * L<Language::SX::Library::Quoting>

=back

=head2 regular expressions

=over

=item * L<Language::SX/"Data Types">

=item * L<Language::SX::Library::Data::Regex>

=back

=head2 roles

=over

=item * L<Language::SX::Library::Data::Objects/"does?">

=back

=head2 runtime value

=over

=item * L<Language::SX/"Data Types">

=item * L<Language::SX::Runtime::Bareword>

=back

=head2 scoping

=over

=item * L<Language::SX::Library::ScopeHandling/"let">

=item * L<Language::SX::Library::ScopeHandling/"let*">

=item * L<Language::SX::Library::ScopeHandling/"let-rec">

=back

=head2 sequential mapping

=over

=item * L<Language::SX::Library::Data::Hashes/"hash-map">

=item * L<Language::SX::Library::Data::Lists/"map">

=back

=head2 setter

=over

=item * L<Language::SX::Library::Data::Common/"values">

=item * L<Language::SX::Library::Data::Hashes/"hash-ref">

=item * L<Language::SX::Library::Data::Hashes/"hash-splice">

=item * L<Language::SX::Library::Data::Lists/"list-ref">

=item * L<Language::SX::Library::Data::Lists/"list-splice">

=item * L<Language::SX::Library::ScopeHandling/"apply!">

=item * L<Language::SX::Library::ScopeHandling/"set!">

=back

=head2 shortcut

=over

=item * L<Language::SX::Library::ScopeHandling/"-E<gt>">

=item * L<Language::SX::Library::ScopeHandling/"E<lt>-">

=item * L<Language::SX::Library::ScopeHandling/"λ">

=back

=head2 strings

=over

=item * L<Language::SX/"Data Types">

=item * L<Language::SX::Library::Data::Strings>

=back

=head2 type objects

=over

=item * L<Language::SX/"Data Types">

=item * L<Language::SX::Library::Data::Objects/"object-invocant">

=item * L<Language::SX::Library::ScopeHandling/"lambda">

=item * L<Language::SX::Library::Types>

=back

=head2 type predicate

=over

=item * L<Language::SX::Library::Data::Common/"defined?">

=item * L<Language::SX::Library::Data::Hashes/"hash?">

=item * L<Language::SX::Library::Data::Lists/"list?">

=item * L<Language::SX::Library::Data::Pairs/"pair?">

=item * L<Language::SX::Library::Data::Pairs/"pairs?">

=item * L<Language::SX::Library::Data::Regex/"regex?">

=item * L<Language::SX::Library::Data::Strings/"string?">

=item * L<Language::SX::Library::Types/"type?">

=back

=head2 upper-case

=over

=item * L<Language::SX::Library::Data::Strings/"upper">

=item * L<Language::SX::Library::Data::Strings/"upper-first">

=back

=head2 value collection

=over

=item * L<Language::SX::Library::Data::Lists/"gather">

=back

=head2 variables

=over

=item * L<Language::SX/"Variables">

=item * L<Language::SX::Library::ScopeHandling/"define">

=item * L<Language::SX::Library::ScopeHandling/"lambda">

=item * L<Language::SX::Library::ScopeHandling/"let">

=item * L<Language::SX::Library::ScopeHandling/"let*">

=item * L<Language::SX::Library::ScopeHandling/"let-rec">

=item * L<Language::SX::Library::Types/"import/types">

=back

=head1 SEE ALSO

=over

=item * L<Language::SX>

=back

=head1 LICENSE AND COPYRIGHT

See L<Language::SX> for information about license and copyright.

=cut